
"""
Module containing only html v5 tags. All deprecated tags have been removed.
"""

from .common import (
    A,
    ABBR,
    ACRONYM,
    ADDRESS,
    APPLET,
    AREA,
    # ARTICLE,
    # ASIDE,
    # AUDIO,
    B,
    BASE,
    BASEFONT,
    # BDI,
    BDO,
    BIG,
    BLOCKQUOTE,
    BODY,
    BR,
    BUTTON,
    Body,
    # CANVAS,
    CAPTION,
    CAT,
    CENTER,
    CITE,
    CODE,
    COL,
    COLGROUP,
    COMMENT,
    CONDITIONAL_COMMENT,
    # DATALIST,
    DD,
    DEL,
    # DETAILS,
    DFN,
    # DIALOG,
    DIR,
    DIV,
    DL,
    DT,
    EM,
    # EMBED,
    FIELDSET,
    # FIGCAPTION,
    # FIGURE,
    FONT,
    # FOOTER,
    FORM,
    FRAME,
    FRAMESET,
    Form,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HEAD,
    # HEADER,
    HR,
    HTML,
    HTMLDoc,
    Hyper,
    I,
    IFRAME,
    IMG,
    INPUT,
    INS,
    Image,
    Javascript,
    KBD,
    # KEYGEN,
    LABEL,
    LEGEND,
    LI,
    LINK,
    # MAIN,
    MAP,
    # MARK,
    MENU,
    # MENUITEM,
    META,
    # METER,
    # NAV,
    NBSP,
    NOFRAMES,
    NOSCRIPT,
    OBJECT,
    OL,
    OPTGROUP,
    OPTION,
    # OUTPUT,
    P,
    PARAM,
    PRE,
    # PROGRESS,
    Q,
    # RP,
    # RT,
    # RUBY,
    S,
    SAMP,
    SCRIPT,
    # SECTION,
    SELECT,
    SMALL,
    # SOURCE,
    SPAN,
    STRIKE,
    STRONG,
    STYLE,
    SUB,
    # SUMMARY,
    SUP,
    TABLE,
    TBODY,
    TD,
    TEXTAREA,
    TFOOT,
    TH,
    THEAD,
    # TIME,
    TITLE,
    TR,
    # TRACK,
    TT,
    U,
    UL,
    VAR,
    # VIDEO,
    # WBR,
    XML,
    XMLEntity,
    XMLNode,
    XMP,
    xmlescape,
    xmlunescape
)

__all__ = [
    'A', 'ABBR', 'ACRONYM', 'ADDRESS', 'APPLET', 'AREA', 'B', 'BASE',
    'BASEFONT', 'BDO', 'BIG', 'BLOCKQUOTE', 'BODY', 'BR', 'BUTTON', 'Body',
    'CAPTION', 'CAT', 'CENTER', 'CITE', 'CODE', 'COL', 'COLGROUP', 'COMMENT',
    'CONDITIONAL_COMMENT', 'DD', 'DEL', 'DFN', 'DIR', 'DIV', 'DL', 'DT', 'EM',
    'FIELDSET', 'FONT', 'FORM', 'FRAME', 'FRAMESET', 'Form', 'H1', 'H2', 'H3',
    'H4', 'H5', 'H6', 'HEAD', 'HR', 'HTML', 'HTMLDoc', 'Hyper', 'I', 'IFRAME',
    'IMG', 'INPUT', 'INS', 'Image', 'Javascript', 'KBD', 'LABEL', 'LEGEND',
    'LI', 'LINK', 'MAP', 'MENU', 'META', 'NBSP', 'NOFRAMES', 'NOSCRIPT',
    'OBJECT', 'OL', 'OPTGROUP', 'OPTION', 'P', 'PARAM', 'PRE', 'Q', 'S',
    'SAMP', 'SCRIPT', 'SELECT', 'SMALL', 'SPAN', 'STRIKE', 'STRONG', 'STYLE',
    'SUB', 'SUP', 'TABLE', 'TBODY', 'TD', 'TEXTAREA', 'TFOOT', 'TH', 'THEAD',
    'TITLE', 'TR', 'TT', 'U', 'UL', 'VAR', 'XML', 'XMLEntity', 'XMLNode',
    'XMP', 'xmlescape', 'xmlunescape'
]
